export const SET_INITIAL_INGREDIENTS = "SET_INITIAL_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_PURCHASING = "SET_PURCHASING";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
